/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/cavern-collision-a.glb -T -M 
Files: ./public/cavern-collision-a.glb [5.5KB] > /home/george/Projects/EcctrlAdvanced/cavern-collision-a-transformed.glb [1.42KB] (74%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model({materialProps, ...props}) {
  const { nodes } = useGLTF('/cavern-collision-a-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} position={[0, -1.003, 0]} scale={[25, 0.244, 2.72]}>
        <meshBasicMaterial {...materialProps} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/cavern-collision-a-transformed.glb')
