/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Demon-packed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group name="CharacterArmature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes.Root} />
          </group>
          <group name="Demon" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <group position={[-0.023, -0.008, -0.015]} scale={0}>
              <skinnedMesh
                name="mesh_0"
                geometry={nodes.mesh_0.geometry}
                material={materials.Demon_Main}
                skeleton={nodes.mesh_0.skeleton}
              />
              <skinnedMesh
                name="mesh_0_1"
                geometry={nodes.mesh_0_1.geometry}
                material={materials.Black}
                skeleton={nodes.mesh_0_1.skeleton}
              />
              <skinnedMesh
                name="mesh_0_2"
                geometry={nodes.mesh_0_2.geometry}
                material={materials.Eye_White}
                skeleton={nodes.mesh_0_2.skeleton}
              />
              <skinnedMesh
                name="mesh_0_3"
                geometry={nodes.mesh_0_3.geometry}
                material={materials.Eye_Black}
                skeleton={nodes.mesh_0_3.skeleton}
              />
            </group>
          </group>
          <group name="Trident" position={[1.895, 1.734, -0.17]} scale={75.326}>
            <skinnedMesh
              name="mesh_1"
              geometry={nodes.mesh_1.geometry}
              material={materials.Black}
              skeleton={nodes.mesh_1.skeleton}
              position={[-0.023, -0.008, -0.015]}
              scale={0}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Demon-packed.glb')